Onboarding does not work without chart title
ffg-seva/onboarding-prototype pull request #116
Opened 2022-07-07 09:12 UTC by dvsilviyageo

closes #114 
Summary:
* In the core package of each chart, where the messages are added, it is checked whether the chart has title if not 'chartTitle' is not added to the message.

screenshots:
![image](https://user-images.githubusercontent.com/104566246/177737534-a4b979c3-0c65-42a5-bbfd-c2b01339bfb0.png)

2022-07-08 08:25 UTC, dvdanielamoitzi requested changes

2022-07-08 08:25 UTC, dvdanielamoitzi commented on packages/core/src/bar-chart.ts
> +    messages = [
this is lots of code duplication. please create the messages array outside the if and then just push the title message inside the if to the messages array

2022-07-08 08:25 UTC, dvdanielamoitzi commented on packages/core/src/change-matrix.ts
> +    messages = [
same here. please create the array with common messages outside the if and only push the other messages to this array inside the if

2022-07-08 08:25 UTC, dvdanielamoitzi commented on packages/core/src/horizon-graph.ts
> +    messages = [
same here

2022-07-08 08:25 UTC, dvdanielamoitzi commented on packages/core/src/scatterplot.ts
> +        anchor: getAnchor(spec.type, visElement),
same here

2022-07-08 09:41 UTC, dvsilviyageo commented on packages/core/src/treemap.ts
> +    messages = [
I have refactored the code to remove the code duplication and made a new commit

2022-07-08 10:04 UTC, dvdanielamoitzi requested changes

2022-07-08 10:04 UTC, dvdanielamoitzi commented on packages/core/src/horizon-graph.ts
> +  messages = [
```suggestion
 const messages: IOnboardingMessage[] = [
```

2022-07-08 10:04 UTC, dvdanielamoitzi commented on packages/core/src/scatterplot.ts
> +  let messages: IOnboardingMessage[];
```suggestion
  ) as IOnboardingStage;
```

2022-07-08 10:04 UTC, dvdanielamoitzi commented on packages/core/src/scatterplot.ts
> +  messages = [
```suggestion
  const messages: IOnboardingMessage[] = [
```

2022-07-08 10:04 UTC, dvdanielamoitzi commented on packages/core/src/treemap.ts
> +  messages = [
```suggestion
  const messages: IOnboardingMessage[] = [
```

2022-07-19 11:18 UTC, dvdanielamoitzi approved these changes

2022-07-19 11:18 UTC, merged